version: '3.9'

services:
  postgres: 
    image: "postgres:15.2-alpine"
    ports:
      - "5555:5432"
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres_booking
      POSTGRES_DB: db_bookings
    volumes:
      - "./database/postgres/:/var/lib/postgresql/data/"

  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - "6666:6379"
    volumes:
      - ./database/redis:/data
