// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package dbrepo

import (
	"context"
)

type Querier interface {
	CreateHall(ctx context.Context, arg CreateHallParams) (*TbHall, error)
	CreateMovie(ctx context.Context, arg CreateMovieParams) (*TbMovie, error)
	CreatePayment(ctx context.Context, arg CreatePaymentParams) (*TbPayment, error)
	CreateRole(ctx context.Context, arg CreateRoleParams) (*TbRole, error)
	CreateSeat(ctx context.Context, arg CreateSeatParams) (*TbSeat, error)
	CreateShowtime(ctx context.Context, arg CreateShowtimeParams) (*TbShowtime, error)
	CreateTheater(ctx context.Context, arg CreateTheaterParams) (*TbTheater, error)
	CreateTicket(ctx context.Context, arg CreateTicketParams) (*TbTicket, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (*TbUser, error)
	DeleteHall(ctx context.Context) (*TbHall, error)
	DeleteMovie(ctx context.Context, id int64) (*TbMovie, error)
	DeletePayment(ctx context.Context) (*TbPayment, error)
	DeleteSeat(ctx context.Context) (*TbSeat, error)
	DeleteShowtime(ctx context.Context, id int64) (*TbShowtime, error)
	DeleteTheater(ctx context.Context) (*TbTheater, error)
	DeleteTicket(ctx context.Context) (*TbTicket, error)
	DeleteUser(ctx context.Context, arg DeleteUserParams) (*TbUser, error)
	GetHall(ctx context.Context, id int64) (*TbHall, error)
	GetMovie(ctx context.Context, id int64) (*TbMovie, error)
	GetPayment(ctx context.Context, id int64) (*TbPayment, error)
	GetRole(ctx context.Context, id int64) (*TbRole, error)
	GetRoles(ctx context.Context, arg GetRolesParams) ([]*TbRole, error)
	GetSeat(ctx context.Context, id int64) (*TbSeat, error)
	GetShowtime(ctx context.Context, id int64) (*TbShowtime, error)
	GetTheater(ctx context.Context, id int64) (*TbTheater, error)
	GetTicket(ctx context.Context, id int64) (*TbTicket, error)
	GetUser(ctx context.Context, id int64) (*TbUser, error)
	GetUserByPhone(ctx context.Context, phoneNumber string) (*TbUser, error)
	ListHalls(ctx context.Context, arg ListHallsParams) ([]*TbHall, error)
	ListMovies(ctx context.Context, arg ListMoviesParams) ([]*TbMovie, error)
	ListPayments(ctx context.Context, arg ListPaymentsParams) ([]*TbPayment, error)
	ListSeats(ctx context.Context, arg ListSeatsParams) ([]*TbSeat, error)
	ListShowtimes(ctx context.Context, arg ListShowtimesParams) ([]*TbShowtime, error)
	ListTheaters(ctx context.Context, arg ListTheatersParams) ([]*TbTheater, error)
	ListTickets(ctx context.Context, arg ListTicketsParams) ([]*TbTicket, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]*TbUser, error)
	UpdateHall(ctx context.Context, arg UpdateHallParams) (*TbHall, error)
	UpdateMovie(ctx context.Context, arg UpdateMovieParams) (*TbMovie, error)
	UpdatePayment(ctx context.Context, arg UpdatePaymentParams) (*TbPayment, error)
	UpdateRole(ctx context.Context, arg UpdateRoleParams) (*TbRole, error)
	UpdateSeat(ctx context.Context, arg UpdateSeatParams) (*TbSeat, error)
	UpdateShowtime(ctx context.Context, arg UpdateShowtimeParams) (*TbShowtime, error)
	UpdateTheater(ctx context.Context, arg UpdateTheaterParams) (*TbTheater, error)
	UpdateTicket(ctx context.Context, arg UpdateTicketParams) (*TbTicket, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (*TbUser, error)
}

var _ Querier = (*Queries)(nil)
