// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0
// source: roles.sql

package dbrepo

import (
	"context"
)

const GetRole = `-- name: GetRole :one
SELECT id, name, code, description, created_at, updated_at, deleted_at FROM tb_roles WHERE id = $1 AND deleted_at IS NULL LIMIT 1
`

func (q *Queries) GetRole(ctx context.Context, id int64) (*TbRole, error) {
	row := q.queryRow(ctx, q.getRoleStmt, GetRole, id)
	var i TbRole
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Code,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return &i, err
}

const GetRoles = `-- name: GetRoles :many
SELECT id, name, code, description, created_at, updated_at, deleted_at FROM tb_roles WHERE deleted_at IS NULL ORDER BY id LIMIT $1 OFFSET $2
`

type GetRolesParams struct {
	Limit  int32 `db:"limit" json:"limit"`
	Offset int32 `db:"offset" json:"offset"`
}

func (q *Queries) GetRoles(ctx context.Context, arg GetRolesParams) ([]*TbRole, error) {
	rows, err := q.query(ctx, q.getRolesStmt, GetRoles, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*TbRole{}
	for rows.Next() {
		var i TbRole
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Code,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
