// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package db

import (
	"time"
)

type TbHall struct {
	ID         int64      `json:"id"`
	TheaterID  int64      `json:"theater_id"`
	Name       string     `json:"name"`
	TotalSeats *int32     `json:"total_seats"`
	CreatedAt  time.Time  `json:"created_at"`
	UpdatedAt  time.Time  `json:"updated_at"`
	DeletedAt  *time.Time `json:"deleted_at"`
}

type TbMovie struct {
	ID          int64     `json:"id"`
	Title       string    `json:"title"`
	ReleaseDate time.Time `json:"release_date"`
	// 导演
	Director string `json:"director"`
	// 海报/封面
	Poster string `json:"poster"`
	// 时长，单位: 分钟
	Duration int32 `json:"duration"`
	// 类型
	Genre *string `json:"genre"`
	// 主演
	Star        *string    `json:"star"`
	Description *string    `json:"description"`
	CreatedAt   time.Time  `json:"created_at"`
	UpdatedAt   time.Time  `json:"updated_at"`
	DeletedAt   *time.Time `json:"deleted_at"`
}

type TbPayment struct {
	ID       int64  `json:"id"`
	UserID   *int64 `json:"user_id"`
	TicketID *int64 `json:"ticket_id"`
	// 电影票数
	NumberOfSeats int32     `json:"NumberOfSeats"`
	PaymentDate   time.Time `json:"payment_date"`
	// 支付方式
	PaymentMethod string `json:"payment_method"`
	// 支付总额, 单位：分
	PaymentAmount int32      `json:"payment_amount"`
	CreatedAt     time.Time  `json:"created_at"`
	UpdatedAt     time.Time  `json:"updated_at"`
	DeletedAt     *time.Time `json:"deleted_at"`
}

type TbRole struct {
	ID          int64      `json:"id"`
	Name        string     `json:"name"`
	Code        string     `json:"code"`
	Description *string    `json:"description"`
	CreatedAt   time.Time  `json:"created_at"`
	UpdatedAt   time.Time  `json:"updated_at"`
	DeletedAt   *time.Time `json:"deleted_at"`
}

type TbSeat struct {
	ID        int64 `json:"id"`
	HallID    int64 `json:"hall_id"`
	ColNumber int32 `json:"col_number"`
	RowNumber int32 `json:"row_number"`
	// 状态: A、B、N, 分别是: 可用、被预订、损坏
	Status    string     `json:"status"`
	CreatedAt time.Time  `json:"created_at"`
	UpdatedAt time.Time  `json:"updated_at"`
	DeletedAt *time.Time `json:"deleted_at"`
}

type TbShowtime struct {
	ID      int64 `json:"id"`
	MovieID int64 `json:"movie_id"`
	HallID  int64 `json:"hall_id"`
	// 放映时间
	StartTime time.Time `json:"start_time"`
	// 结束时间
	EndTime   time.Time  `json:"end_time"`
	CreatedAt time.Time  `json:"created_at"`
	UpdatedAt time.Time  `json:"updated_at"`
	DeletedAt *time.Time `json:"deleted_at"`
}

type TbTheater struct {
	ID        int64      `json:"id"`
	Name      string     `json:"name"`
	Location  *string    `json:"location"`
	CreatedAt time.Time  `json:"created_at"`
	UpdatedAt time.Time  `json:"updated_at"`
	DeletedAt *time.Time `json:"deleted_at"`
}

type TbTicket struct {
	ID         int64  `json:"id"`
	UserID     *int64 `json:"user_id"`
	ShowtimeID int64  `json:"showtime_id"`
	SeatID     int64  `json:"seat_id"`
	// 单价，单位: 分
	Price int32 `json:"price"`
	// 下订日期，被预订时设置时间
	BookingDate *time.Time `json:"booking_date"`
	// 支付状态:Y/N
	PaymentStatus *string    `json:"payment_status"`
	CreatedAt     time.Time  `json:"created_at"`
	UpdatedAt     time.Time  `json:"updated_at"`
	DeletedAt     *time.Time `json:"deleted_at"`
}

type TbUser struct {
	ID          int64      `json:"id"`
	RoleID      *int64     `json:"role_id"`
	PhoneNumber string     `json:"phone_number"`
	Password    *string    `json:"password"`
	Name        string     `json:"name"`
	Avatar      *string    `json:"avatar"`
	Openid      *string    `json:"openid"`
	Unionid     *string    `json:"unionid"`
	CreatedAt   time.Time  `json:"created_at"`
	UpdatedAt   time.Time  `json:"updated_at"`
	DeletedAt   *time.Time `json:"deleted_at"`
}
