// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package db

import (
	"context"
)

type Querier interface {
	CreateUser(ctx context.Context, arg CreateUserParams) (*TbUser, error)
	GetUser(ctx context.Context, id int64) (*TbUser, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (*TbUser, error)
}

var _ Querier = (*Queries)(nil)
